### PR TITLE
Add retain_shape option to condense_segments

### PR DESCRIPTION
**Pull request by jennylovesreading**

### CODE REVIEW

**Comment by rileyschack** [comment]
@jennylovesreading I'd prefer a solution without joining back to the original dataframe. I suppose the issue is that the date columns get replaced with the "condensed" values.

**Comment by jennylovesreading** [comment]
@rileyschack Just a clarification but 

1. Return the original DataFrame, with 2 additional columns for start/end dates

means that the original as well as the condensed dates are present.

**Comment by rileyschack** [comment]
@jennylovesreading Looks like the code needs to be formatted with `black`.

**Comment by WesRoach** [comment]
Thanks for working on this @jennylovesreading!

**Pull request merged**
